### docker-compose file for development environment
#
version: "3.7"
services:

  postgres:
    image: postgres
    networks:
      - mynet
    environment:
      - POSTGRES_PASSWORD=3sf2reRer
    ports:
      - "127.0.0.1:5432:5432"
    hostname: postgres

networks:
  mynet: